DELETE http://localhost:8080/events/1
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3Q0NTZAZXhhbXBsZS5jb20iLCJleHAiOjE3MDQ2ODUzNTIsInVzZXJJZCI6Mn0.Q8zggUCJy0RUpSWu1wzweq2QAEyn8OAbUFU7yNaiZB0